/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-05-05 16:01:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Hostel Management System</title>\n");
      out.write("<style>\n");
      out.write("    body { \n");
      out.write("        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; \n");
      out.write("        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n");
      out.write("        margin: 0; \n");
      out.write("        padding: 40px 20px; \n");
      out.write("        min-height: 100vh;\n");
      out.write("        color: white;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("    .header {\n");
      out.write("        text-align: center;\n");
      out.write("        margin-bottom: 40px;\n");
      out.write("    }\n");
      out.write("    .header h1 {\n");
      out.write("        font-size: 3em;\n");
      out.write("        margin: 0 0 10px 0;\n");
      out.write("        text-shadow: 2px 2px 4px rgba(0,0,0,0.2);\n");
      out.write("    }\n");
      out.write("    .header p {\n");
      out.write("        font-size: 1.2em;\n");
      out.write("        margin: 0;\n");
      out.write("        opacity: 0.9;\n");
      out.write("    }\n");
      out.write("    .container { \n");
      out.write("        max-width: 1000px; \n");
      out.write("        margin: 0 auto; \n");
      out.write("        display: grid;\n");
      out.write("        grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n");
      out.write("        gap: 20px;\n");
      out.write("    }\n");
      out.write("    .card {\n");
      out.write("        background: white;\n");
      out.write("        border-radius: 12px;\n");
      out.write("        padding: 30px 20px;\n");
      out.write("        text-align: center;\n");
      out.write("        box-shadow: 0 8px 20px rgba(0,0,0,0.15);\n");
      out.write("        transition: transform 0.2s, box-shadow 0.2s;\n");
      out.write("        display: flex;\n");
      out.write("        flex-direction: column;\n");
      out.write("        justify-content: space-between;\n");
      out.write("    }\n");
      out.write("    .card:hover {\n");
      out.write("        transform: translateY(-5px);\n");
      out.write("        box-shadow: 0 12px 25px rgba(0,0,0,0.2);\n");
      out.write("    }\n");
      out.write("    .icon {\n");
      out.write("        font-size: 3em;\n");
      out.write("        margin-bottom: 15px;\n");
      out.write("    }\n");
      out.write("    .card h3 {\n");
      out.write("        color: #333;\n");
      out.write("        margin: 0 0 10px 0;\n");
      out.write("        font-size: 1.4em;\n");
      out.write("    }\n");
      out.write("    .card p {\n");
      out.write("        color: #666;\n");
      out.write("        margin: 0 0 20px 0;\n");
      out.write("        font-size: 0.95em;\n");
      out.write("    }\n");
      out.write("    .btn {\n");
      out.write("        display: block;\n");
      out.write("        width: 100%;\n");
      out.write("        padding: 12px;\n");
      out.write("        border-radius: 8px;\n");
      out.write("        color: white;\n");
      out.write("        text-decoration: none;\n");
      out.write("        font-weight: bold;\n");
      out.write("        font-size: 1.1em;\n");
      out.write("        transition: opacity 0.2s;\n");
      out.write("        box-sizing: border-box;\n");
      out.write("    }\n");
      out.write("    .btn:hover {\n");
      out.write("        opacity: 0.9;\n");
      out.write("    }\n");
      out.write("    .btn-green { background-color: #198754; }\n");
      out.write("    .btn-blue { background-color: #0d6efd; }\n");
      out.write("    .btn-yellow { background-color: #ffc107; color: #000; }\n");
      out.write("    .btn-red { background-color: #dc3545; }\n");
      out.write("    .btn-cyan { background-color: #0dcaf0; color: #000; }\n");
      out.write("    .error { color: #ffcccc; text-align: center; margin-bottom: 20px; font-weight: bold; background: rgba(220, 53, 69, 0.8); padding: 10px; border-radius: 5px; max-width: 800px; margin-left: auto; margin-right: auto;}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"header\">\n");
      out.write("    <h1>Hostel Management System</h1>\n");
      out.write("    <p>Manage students, rooms, and generate reports</p>\n");
      out.write("</div>\n");
      out.write("\n");
 
    String error = request.getParameter("error");
    if (error != null) {

      out.write("\n");
      out.write("    <div class=\"error\">");
      out.print( error );
      out.write("</div>\n");
 } 
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("    <!-- Card 1 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"icon\">&#10010;</div>\n");
      out.write("            <h3>Add Student</h3>\n");
      out.write("            <p>Register a new student in the hostel</p>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"studentadd.jsp\" class=\"btn btn-green\">Add Student</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Card 2 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"icon\">&#128203;</div>\n");
      out.write("            <h3>Display Students</h3>\n");
      out.write("            <p>View all registered students</p>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"DisplayStudentsServlet\" class=\"btn btn-blue\">View All</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Card 3 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"icon\">&#9998;</div>\n");
      out.write("            <h3>Update Student</h3>\n");
      out.write("            <p>Modify existing student details</p>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"DisplayStudentsServlet\" class=\"btn btn-yellow\">Update</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Card 4 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"icon\">&#128465;</div>\n");
      out.write("            <h3>Delete Student</h3>\n");
      out.write("            <p>Remove a student from records</p>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"DisplayStudentsServlet\" class=\"btn btn-red\">Delete</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Card 5 -->\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <div>\n");
      out.write("            <div class=\"icon\">&#128202;</div>\n");
      out.write("            <h3>Reports</h3>\n");
      out.write("            <p>View hostel statistics and reports</p>\n");
      out.write("        </div>\n");
      out.write("        <a href=\"reports.jsp\" class=\"btn btn-cyan\">Reports</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
