/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-05-05 16:05:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.Student;

public final class studentupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.model.Student");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Update Student</title>\n");
      out.write("<style>\n");
      out.write("    body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; }\n");
      out.write("    .container { max-width: 500px; margin: auto; background: white; padding: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }\n");
      out.write("    h2 { text-align: center; color: #333; }\n");
      out.write("    form { display: flex; flex-direction: column; gap: 10px; }\n");
      out.write("    label { font-weight: bold; }\n");
      out.write("    input[type=\"text\"], input[type=\"number\"], input[type=\"date\"] { padding: 8px; border: 1px solid #ccc; border-radius: 3px; }\n");
      out.write("    input[type=\"submit\"] { padding: 10px; background: #007BFF; color: white; border: none; border-radius: 3px; cursor: pointer; font-size: 16px; }\n");
      out.write("    input[type=\"submit\"]:hover { background: #0056b3; }\n");
      out.write("    .error { color: red; margin-bottom: 10px; }\n");
      out.write("    .back-link { display: block; text-align: center; margin-top: 15px; text-decoration: none; color: #007BFF; }\n");
      out.write("    .back-link:hover { text-decoration: underline; }\n");
      out.write("    .hint { font-size: 12px; color: #888; margin-top: -5px; }\n");
      out.write("    .id-display { background: #e9ecef; padding: 8px; border-radius: 3px; color: #495057; font-weight: bold; }\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("    function validateForm() {\n");
      out.write("        var name = document.getElementById(\"studentName\").value.trim();\n");
      out.write("        var room = document.getElementById(\"roomNumber\").value.trim().toUpperCase();\n");
      out.write("        \n");
      out.write("        var namePattern = /^[a-zA-Z ]+$/;\n");
      out.write("        if (!namePattern.test(name)) {\n");
      out.write("            alert(\"Student Name must contain only letters and spaces.\");\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        var roomPattern = /^[A-Za-z]\\d{1,4}$/;\n");
      out.write("        if (!roomPattern.test(room)) {\n");
      out.write("            alert(\"Room Number must be a letter followed by digits (e.g., A101, B202).\");\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        return true;\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h2>Update Student Details</h2>\n");
      out.write("    ");
 
        String error = request.getParameter("error");
        if (error != null) {
    
      out.write("\n");
      out.write("        <div class=\"error\">");
      out.print( error );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    \n");
      out.write("    ");

        Student student = (Student) request.getAttribute("student");
        if (student != null) {
    
      out.write("\n");
      out.write("    <form action=\"UpdateStudentServlet\" method=\"post\" onsubmit=\"return validateForm();\">\n");
      out.write("        <input type=\"hidden\" name=\"studentID\" value=\"");
      out.print( student.getStudentID() );
      out.write("\">\n");
      out.write("\n");
      out.write("        <label>Student ID:</label>\n");
      out.write("        <div class=\"id-display\">");
      out.print( student.getStudentID() );
      out.write("</div>\n");
      out.write("\n");
      out.write("        <label for=\"studentName\">Student Name:</label>\n");
      out.write("        <input type=\"text\" id=\"studentName\" name=\"studentName\" value=\"");
      out.print( student.getStudentName() );
      out.write("\" required pattern=\"[a-zA-Z ]+\" title=\"Only letters and spaces allowed\">\n");
      out.write("        <div class=\"hint\">Only letters and spaces allowed</div>\n");
      out.write("\n");
      out.write("        <label for=\"roomNumber\">Room Number:</label>\n");
      out.write("        <input type=\"text\" id=\"roomNumber\" name=\"roomNumber\" value=\"");
      out.print( student.getRoomNumber() );
      out.write("\" required pattern=\"[A-Za-z]\\d{1,4}\" title=\"Letter followed by digits (e.g., A101)\">\n");
      out.write("        <div class=\"hint\">Format: A101, B202, C3 etc.</div>\n");
      out.write("\n");
      out.write("        <label for=\"admissionDate\">Admission Date:</label>\n");
      out.write("        <input type=\"date\" id=\"admissionDate\" name=\"admissionDate\" value=\"");
      out.print( student.getAdmissionDate() );
      out.write("\" required>\n");
      out.write("\n");
      out.write("        <label for=\"feesPaid\">Fees Paid (INR):</label>\n");
      out.write("        <input type=\"number\" id=\"feesPaid\" name=\"feesPaid\" value=\"");
      out.print( student.getFeesPaid() );
      out.write("\" min=\"0\" step=\"0.01\" required>\n");
      out.write("\n");
      out.write("        <label for=\"pendingFees\">Pending Fees (INR):</label>\n");
      out.write("        <input type=\"number\" id=\"pendingFees\" name=\"pendingFees\" value=\"");
      out.print( student.getPendingFees() );
      out.write("\" min=\"0\" step=\"0.01\" required>\n");
      out.write("\n");
      out.write("        <input type=\"submit\" value=\"Update Student\">\n");
      out.write("    </form>\n");
      out.write("    ");

        } else {
    
      out.write("\n");
      out.write("        <p class=\"error\">Student details not found.</p>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("    <a href=\"DisplayStudentsServlet\" class=\"back-link\">Back to Student List</a>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
