/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.117
 * Generated at: 2026-05-05 16:10:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.model.Student;

public final class studentdisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Student");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>All Students</title>\n");
      out.write("<style>\n");
      out.write("    body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; }\n");
      out.write("    .container { max-width: 1000px; margin: auto; background: white; padding: 20px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }\n");
      out.write("    h2 { text-align: center; color: #333; }\n");
      out.write("    table { width: 100%; border-collapse: collapse; margin-top: 20px; }\n");
      out.write("    table, th, td { border: 1px solid #ddd; }\n");
      out.write("    th, td { padding: 12px; text-align: left; }\n");
      out.write("    th { background-color: #007BFF; color: white; }\n");
      out.write("    tr:nth-child(even) { background-color: #f2f2f2; }\n");
      out.write("    .action-links a { margin-right: 10px; text-decoration: none; color: #007BFF; }\n");
      out.write("    .action-links a:hover { text-decoration: underline; }\n");
      out.write("    .action-links .delete-btn { background: #dc3545; border: none; color: white; cursor: pointer; font-size: 14px; padding: 5px 12px; border-radius: 3px; text-decoration: none; }\n");
      out.write("    .action-links .delete-btn:hover { background: #c82333; }\n");
      out.write("    .action-links .edit-btn { background: #007BFF; color: white; padding: 5px 12px; border-radius: 3px; text-decoration: none; font-size: 14px; }\n");
      out.write("    .action-links .edit-btn:hover { background: #0056b3; }\n");
      out.write("    .back-link { display: block; text-align: center; margin-top: 20px; text-decoration: none; color: #007BFF; }\n");
      out.write("    .back-link:hover { text-decoration: underline; }\n");
      out.write("    .error { color: red; text-align: center; margin-bottom: 10px; }\n");
      out.write("\n");
      out.write("    /* Delete Confirmation Modal */\n");
      out.write("    .modal-overlay {\n");
      out.write("        display: none;\n");
      out.write("        position: fixed;\n");
      out.write("        top: 0; left: 0; width: 100%; height: 100%;\n");
      out.write("        background: rgba(0,0,0,0.5);\n");
      out.write("        z-index: 1000;\n");
      out.write("        justify-content: center;\n");
      out.write("        align-items: center;\n");
      out.write("    }\n");
      out.write("    .modal-overlay.active { display: flex; }\n");
      out.write("    .modal-box {\n");
      out.write("        background: white;\n");
      out.write("        border-radius: 8px;\n");
      out.write("        padding: 30px;\n");
      out.write("        max-width: 400px;\n");
      out.write("        width: 90%;\n");
      out.write("        text-align: center;\n");
      out.write("        box-shadow: 0 5px 20px rgba(0,0,0,0.3);\n");
      out.write("    }\n");
      out.write("    .modal-box h3 { color: #dc3545; margin: 0 0 15px 0; }\n");
      out.write("    .modal-box p { color: #333; margin: 0 0 20px 0; }\n");
      out.write("    .modal-actions { display: flex; gap: 10px; justify-content: center; }\n");
      out.write("    .modal-actions button {\n");
      out.write("        padding: 10px 25px;\n");
      out.write("        border: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("        cursor: pointer;\n");
      out.write("        font-size: 15px;\n");
      out.write("        font-weight: bold;\n");
      out.write("    }\n");
      out.write("    .btn-confirm-delete { background: #dc3545; color: white; }\n");
      out.write("    .btn-confirm-delete:hover { background: #c82333; }\n");
      out.write("    .btn-cancel { background: #6c757d; color: white; }\n");
      out.write("    .btn-cancel:hover { background: #5a6268; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <h2>All Registered Students</h2>\n");
      out.write("    ");
 
        String error = request.getParameter("error");
        if (error != null) {
    
      out.write("\n");
      out.write("        <div class=\"error\">");
      out.print( error );
      out.write("</div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    \n");
      out.write("    <table>\n");
      out.write("        <thead>\n");
      out.write("            <tr>\n");
      out.write("                <th>Sr. No.</th>\n");
      out.write("                <th>Student ID</th>\n");
      out.write("                <th>Student Name</th>\n");
      out.write("                <th>Room Number</th>\n");
      out.write("                <th>Admission Date</th>\n");
      out.write("                <th>Fees Paid</th>\n");
      out.write("                <th>Pending Fees</th>\n");
      out.write("                <th>Actions</th>\n");
      out.write("            </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("            ");

                List<Student> listStudents = (List<Student>) request.getAttribute("listStudents");
                if (listStudents != null && !listStudents.isEmpty()) {
                    int srNo = 1;
                    for (Student student : listStudents) {
            
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td>");
      out.print( srNo++ );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( student.getStudentID() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( student.getStudentName() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( student.getRoomNumber() );
      out.write("</td>\n");
      out.write("                    <td>");
      out.print( student.getAdmissionDate() );
      out.write("</td>\n");
      out.write("                    <td>&#8377; ");
      out.print( String.format("%.2f", student.getFeesPaid()) );
      out.write("</td>\n");
      out.write("                    <td>&#8377; ");
      out.print( String.format("%.2f", student.getPendingFees()) );
      out.write("</td>\n");
      out.write("                    <td class=\"action-links\">\n");
      out.write("                        <a href=\"UpdateStudentServlet?studentID=");
      out.print( student.getStudentID() );
      out.write("\" class=\"edit-btn\">Edit</a>\n");
      out.write("                        <button type=\"button\" class=\"delete-btn\"\n");
      out.write("                            data-id=\"");
      out.print( student.getStudentID() );
      out.write("\"\n");
      out.write("                            data-name=\"");
      out.print( student.getStudentName() );
      out.write("\"\n");
      out.write("                            onclick=\"showDeleteModal(this)\">Delete</button>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            ");

                    }
                } else {
            
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                    <td colspan=\"8\" style=\"text-align: center;\">No students found.</td>\n");
      out.write("                </tr>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </tbody>\n");
      out.write("    </table>\n");
      out.write("    <a href=\"index.jsp\" class=\"back-link\">Back to Home</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Delete Confirmation Modal -->\n");
      out.write("<div class=\"modal-overlay\" id=\"deleteModal\">\n");
      out.write("    <div class=\"modal-box\">\n");
      out.write("        <h3>Confirm Delete</h3>\n");
      out.write("        <p>Are you sure you want to delete student:<br><strong id=\"deleteStudentInfo\"></strong></p>\n");
      out.write("        <div class=\"modal-actions\">\n");
      out.write("            <button class=\"btn-cancel\" onclick=\"hideDeleteModal()\">Cancel</button>\n");
      out.write("            <form id=\"deleteForm\" action=\"DeleteStudentServlet\" method=\"post\" style=\"display:inline;\">\n");
      out.write("                <input type=\"hidden\" name=\"studentID\" id=\"deleteStudentID\" value=\"\">\n");
      out.write("                <button type=\"submit\" class=\"btn-confirm-delete\">Delete</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function showDeleteModal(btn) {\n");
      out.write("        var sid = btn.getAttribute('data-id');\n");
      out.write("        var sname = btn.getAttribute('data-name');\n");
      out.write("        document.getElementById('deleteStudentID').value = sid;\n");
      out.write("        document.getElementById('deleteStudentInfo').textContent = sname + ' (ID: ' + sid + ')';\n");
      out.write("        document.getElementById('deleteModal').classList.add('active');\n");
      out.write("    }\n");
      out.write("    function hideDeleteModal() {\n");
      out.write("        document.getElementById('deleteModal').classList.remove('active');\n");
      out.write("    }\n");
      out.write("    // Close modal on overlay click\n");
      out.write("    document.getElementById('deleteModal').addEventListener('click', function(e) {\n");
      out.write("        if (e.target === this) hideDeleteModal();\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
